name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/run-tests.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/e2e.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/run-tests.yml"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/e2e.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  cargo:
    name: "registry / Run cargo tests"
    runs-on: builder
    timeout-minutes: 60

    defaults:
      run:
        working-directory: service

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Setup marine
        uses: fluencelabs/setup-marine@v1

      - name: Build service
        run: ./build.sh

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -Z unstable-options --all -- -D warnings

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3.1.1
        with:
          crate: cargo-nextest
          version: 0.9.22

      - name: Run cargo nextest
        env:
          NEXTEST_RETRIES: 2
          NEXTEST_TEST_THREADS: 1
        run: cargo nextest run --release --all-features --no-fail-fast

  lints:
    name: Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path service/Cargo.toml -- --check
